apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
stringData:
  DJANGO_SUPERUSER_USERNAME: example
  DJANGO_SUPERUSER_PASSWORD: changeme
  DJANGO_SUPERUSER_EMAIL: example@example.com
